# Generated by Django 5.2.7 on 2025-11-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.IntegerField(verbose_name='投票主題編號')),
                ('title', models.CharField(max_length=64, verbose_name='選項文字')),
                ('count', models.IntegerField(default=0, verbose_name='已投票數')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64, verbose_name='投票主題')),
                ('description', models.TextField(verbose_name='說明')),
                ('created', models.DateField(auto_now_add=True, verbose_name='建立時間')),
            ],
        ),
    ]
